config/routes.rb
Darts::Application.routes.draw do
  resources :championships

  resources :tries

  resources :games

  resources :players

  devise_for :users

  root to: "home#index"

end

app/models/championship.rb
class Championship < ActiveRecord::Base
  attr_accessible :name
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :game_type

  belongs_to :winner, :class_name => 'Player'
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name
end

app/models/try.rb
class Try < ActiveRecord::Base
  attr_accessible :amount, :multiplicator, :player_id, :position, :total
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  before_filter :set_championship, only: [:show, :edit, :update, :destroy]

  def index
    @championships = Championship.all
    respond_with(@championships)
  end

  def show
    respond_with(@championship)
  end

  def new
    @championship = Championship.new
    respond_with(@championship)
  end

  def edit
  end

  def create
    @championship = Championship.new(params[:championship])
    @championship.save
    respond_with(@championship)
  end

  def update
    @championship.update_attributes(params[:championship])
    respond_with(@championship)
  end

  def destroy
    @championship.destroy
    respond_with(@championship)
  end

  private
    def set_championship
      @championship = Championship.find(params[:id])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
    respond_with(@games)
  end

  def show
    respond_with(@game)
  end

  def new
    @game = Game.new
    respond_with(@game)
  end

  def edit
  end

  def create
    @game = Game.new(params[:game])
    @game.save
    respond_with(@game)
  end

  def update
    @game.update_attributes(params[:game])
    respond_with(@game)
  end

  def destroy
    @game.destroy
    respond_with(@game)
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
    respond_with(@players)
  end

  def show
    respond_with(@player)
  end

  def new
    @player = Player.new
    respond_with(@player)
  end

  def edit
  end

  def create
    @player = Player.new(params[:player])
    @player.save
    respond_with(@player)
  end

  def update
    @player.update_attributes(params[:player])
    respond_with(@player)
  end

  def destroy
    @player.destroy
    respond_with(@player)
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end
end

app/controllers/tries_controller.rb
class TriesController < ApplicationController
  before_filter :set_try, only: [:show, :edit, :update, :destroy]

  def index
    @tries = Try.all
    respond_with(@tries)
  end

  def show
    respond_with(@try)
  end

  def new
    @try = Try.new
    respond_with(@try)
  end

  def edit
  end

  def create
    @try = Try.new(params[:try])
    @try.save
    respond_with(@try)
  end

  def update
    @try.update_attributes(params[:try])
    respond_with(@try)
  end

  def destroy
    @try.destroy
    respond_with(@try)
  end

  private
    def set_try
      @try = Try.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tries_helper.rb
module TriesHelper
end

app/views/championships/_form.html.erb
<%= form_for(@championship) do |f| %>
  <% if @championship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@championship.errors.count, "error") %> prohibited this championship from being saved:</h2>

      <ul>
      <% @championship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/championships/edit.html.erb
<h1>Editing championship</h1>

<%= render 'form' %>

<%= link_to 'Show', @championship %> |
<%= link_to 'Back', championships_path %>

app/views/championships/index.html.erb
<h1>Listing championships</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @championships.each do |championship| %>
  <tr>
    <td><%= championship.name %></td>
    <td><%= link_to 'Show', championship %></td>
    <td><%= link_to 'Edit', edit_championship_path(championship) %></td>
    <td><%= link_to 'Destroy', championship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Championship', new_championship_path %>

app/views/championships/new.html.erb
<h1>New championship</h1>

<%= render 'form' %>

<%= link_to 'Back', championships_path %>

app/views/championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @championship.name %>
</p>


<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_type %><br />
    <%= f.text_field :game_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Game type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.game_type %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game type:</b>
  <%= @game.game_type %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Darts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/tries/_form.html.erb
<%= form_for(@try) do |f| %>
  <% if @try.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@try.errors.count, "error") %> prohibited this try from being saved:</h2>

      <ul>
      <% @try.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :multiplicator %><br />
    <%= f.number_field :multiplicator %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.number_field :total %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= f.number_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tries/edit.html.erb
<h1>Editing try</h1>

<%= render 'form' %>

<%= link_to 'Show', @try %> |
<%= link_to 'Back', tries_path %>

app/views/tries/index.html.erb
<h1>Listing tries</h1>

<table>
  <tr>
    <th>Position</th>
    <th>Amount</th>
    <th>Multiplicator</th>
    <th>Total</th>
    <th>Player</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tries.each do |try| %>
  <tr>
    <td><%= try.position %></td>
    <td><%= try.amount %></td>
    <td><%= try.multiplicator %></td>
    <td><%= try.total %></td>
    <td><%= try.player_id %></td>
    <td><%= link_to 'Show', try %></td>
    <td><%= link_to 'Edit', edit_try_path(try) %></td>
    <td><%= link_to 'Destroy', try, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Try', new_try_path %>

app/views/tries/new.html.erb
<h1>New try</h1>

<%= render 'form' %>

<%= link_to 'Back', tries_path %>

app/views/tries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Position:</b>
  <%= @try.position %>
</p>

<p>
  <b>Amount:</b>
  <%= @try.amount %>
</p>

<p>
  <b>Multiplicator:</b>
  <%= @try.multiplicator %>
</p>

<p>
  <b>Total:</b>
  <%= @try.total %>
</p>

<p>
  <b>Player:</b>
  <%= @try.player_id %>
</p>


<%= link_to 'Edit', edit_try_path(@try) %> |
<%= link_to 'Back', tries_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>